### PR TITLE
fix: use selector for JupyterLab dark mode

### LINKED ISSUE #67: Support darkmode
Mystjs supports dark mode, but we need to hook into the correct state / theme for JupyterLab.

cc @agoose77

### LINKED ISSUE #84: Unreadable rendering when using Dark theme
### Describe the bug

This shows the problem - same notebook opened with MyST and "Classic" in dark mode:

image

### Reproduce the bug

Use dark theme.

### List your environment

_No response_

### PR DESCRIPTION
**Pull request by agoose77**
Fixes #67 and fixes #84

### CODE REVIEW

**Comment by agoose77** [comment]
We can do more here; JupyterLab defined variables that themes can override. It's a decision as to whether we respect that or not.

**Comment by rowanc1** [comment]
We can override everything in that tailwind config with variables, I have a local branch starting to play with getting styles inline.

For this PR, I think we can keep it to your change, and get better at styles in a next pr!

**Comment by mcauthorn** [comment]
Thanks all, after following @agoose77 over here from imarkdown (specifically, your {eval} syntax which is huge feature to our use case), I just ran into this with a custom theme that we're designing for Jupyterlab. A couple of questions:

1) In my theme config, which variables are read?
2) Is there a dev branch you could point me to so I could help test?

Thanks again for the activity here, it's looking really promising.

**Comment by mcauthorn** [comment]
Found it, looking good!

**Pull request merged**
