### PR TITLE
🎨 Update for showing exercises

### PR DESCRIPTION
**Pull request by rowanc1**
@mmcky this PR adds support in JupyterLab-MyST for exercises/solutions. We have also added unknown directives, and fixed a citation.

image

The gated directives should also render in a degraded form, which allows you to have the notebook cells editable in the notebook and then when you use myst/jupyterbook it will stitch them together for rendering.

image

### CODE REVIEW

**Comment by rowanc1** [comment]
@agoose77 I will let you have a look if you want in the next few days, but I think this is probably good enough for another patch/minor release. Hopefully easy to merge into your JLab4 branch (minus the yarn-lock).

**Comment by psychemedia** [comment]
This looks really interesting... 
Is there any mechanism for being able to style the background of all the exercise cells? Eg in our course materials, which don't use Sphinx exercise, we use cell tags to style all the cells associated with an exercise or activity.

image

**Comment by agoose77** [comment]
If we add classes to [our rendered exercises](https://github.com/executablebooks/myst-theme/blob/ebc64927ab5de20db09e7410bd450dafc913c79e/packages/myst-to-react/src/exercise.tsx#L164), then one can use `jupyterlab-plugin-playground` to customise the styles in JupyterLab. @rowanc1 thoughts?

**Comment by psychemedia** [comment]
@agoose77 A minimal JupyterLab extension that pretty much just imports custom CSS can also then be used to apply styling to added classes.

**Comment by agoose77** [comment]
@psychemedia that's the thought. Using `jupyterlab-plugin-playground` allows you to avoid distributing this extension yourself (it can be a simple gist file), but it's the same end result.

**Pull request merged**
