### PR TITLE
Bugfix: fix Binder environment / package name

### PR DESCRIPTION
**Pull request by agoose77**
Welp, I managed to miss the fact that the cookiecutter set the Python package name to `jupyterlab-myst` instead of `jupyterlab_myst`. This PR address that alongside other binder issues

### CODE REVIEW

**Review by rowanc1 — APPROVED** [review]
Looks good - let me know when you want this in!

**Comment by agoose77** [comment]
:+1: LGTM :) I'll investigate the CI failure in another PR if needs be.

**Review by choldgraf — APPROVED** [review]

**Review by damianavila — APPROVED** [review]
LGTM as well (modulo the CI is fixed :wink:)

**Comment by agoose77** [comment]
Superseded by #15

**Pull request closed without merging**
