### PR TITLE
Fix failing CI

### PR DESCRIPTION
**Pull request by GlobalMin**
Hi @agoose77 👋 .

I noticed the current main branch is failing due to a linting error, which is my first commit of the two here. Then there is an error stemming from this line in the workflow.yml GH actions file:

`python -c 'from packaging.version import Version; from importlib.metadata import version as version_of; raise SystemExit(Version(version_of('\''jupyterlab'\'')) > Version('\''4.0.6'\''))'`

This I'm less sure how the EB team wants to handle but I modified the max version ` > Version('\''4.0.6'\''))` to ` > Version('\''4.0.7'\''))` since that's the latest jupyterlab version and this constraint in `pyproject.toml` will install the latest 4.x.x version. 

`"python -m pip install 'jupyterlab>=4.0.0,<5'"`

Anyway fixes the CI on my fork. Let me know if any issues with these changes. 

Jameson

### CODE REVIEW

**Comment by rowanc1** [comment]
Linting change looks good. This gets broken every time we release, and we haven't figured out how to change the release infrastructure or patch it before it is committed.

Not sure on the other version change if @agoose77 has specific thoughts there?

**Comment by GlobalMin** [comment]
> Linting change looks good. This gets broken every time we release, and we haven't figured out how to change the release infrastructure or patch it before it is committed.
> 
> Not sure on the other version change if @agoose77 has specific thoughts there?

Sounds good. So this line is what the second change addresses: https://github.com/executablebooks/jupyterlab-myst/blob/4684bc358f7d9be3fe62baccc862c35606c9c488/.github/workflows/build.yml#L46

I'm not sure why tests fail without this patch but when you `pip install jupyterlab` currently it's going to install 4.0.7.

**Comment by GlobalMin** [comment]
@agoose77 bumping for visibility

**Comment by agoose77** [comment]
@GlobalMin thanks for the contribution! I've fixed this separately now, but I appreciate your contribution immensely!

**Pull request closed without merging**
