### PR TITLE
WIP: implement jupyterlab-markup support

### PR DESCRIPTION
**Pull request by agoose77**
This is a WIP PR to add support for MyST rendering to JupyterLab via a `jupyterlab-markup` plugin.

### CODE REVIEW

**Comment by choldgraf** [comment]
yesss!

**Comment by agoose77** [comment]
Hehe, I was already subscribed to [this issue](https://github.com/executablebooks/meta/issues/184)

> yesss! we discussed jupyterlab-markup in a meeting about this yesterday, did somebody ping you or did you just happen to notice this? either way thanks for the PR :-)

**Comment by rowanc1** [comment]
This is so amazing. :) I can't dig in today but should get a chance over the weekend! Any screenshot or gif you can easily show?

Glad the export from markdown-it-myst is now working!

**Comment by agoose77** [comment]
Peek 2021-05-21 17-13

**Comment by rowanc1** [comment]
So cool - you have me very excited about this! Hoping that you appreciate my sarcastic `admonition` comments - [based on data](https://books.google.com/ngrams/graph?content=admonition&year_start=1800&year_end=2019&corpus=28&smoothing=3&direct_url=t1%3B%2Cadmonition%3B%2Cc0#t1%3B%2Cadmonition%3B%2Cc0) at least. :)
Will look at this soon!

**Comment by agoose77** [comment]
@choldgraf I think this is *ready* as far as an initial implementation goes - most of the work is already being done by `markdown-it-myst` and `jupyterlab-markup`. Do you have any requests that are stopping this from being merged?

**Comment by choldgraf** [comment]
@rowanc1 are you fine merging this in? I'm happy to defer to your preferences 👍 

One thing that would help is slightly better documentation. E.g., the README says `pip install jupyterlab-myst`, but it isn't published to PyPI or anything, so steps to install that will definitely work would be helpful

**Comment by agoose77** [comment]
I haven't pushed to PyPI yet because I would like to use this repository for the package metadata. The README will need some more work; right now it's the default as-given by the cookiecutter!

**Comment by rowanc1** [comment]
(I haven't managed to get this up and running yet)

From my understanding, this is mostly extending the `jupyterlab-markup` npm package? Is this where all of the logic for hooking into JupyterLab is? Is there any documentation that shows that library off (I couldn't find it)?

Some small things:
- [ ] restore license file to Executable Books
- [ ] remove yarn-error.log
- [ ] Adding some of the readme back in

Some other curiosities that can be understood later, are around how/where the math rendering is completed, as that is taken out of the MyST block (and we have some logic around numbering that will require that). Any thoughts there or seeing that as difficult using this infrastructure?

**Comment by agoose77** [comment]
@rowanc1 for now, this uses the jupyterlab-markup rendering, which strips out the math markup before markdown rendering, and then restores it afterwards. This is "useful" because it allows users to exchange the math renderer with the existing `jupyterlab-katex`. It *might* be that this is something that jupyterlab-markup should do differently in future, i.e. we completely override the math rendering and let plugins do their own thing if necessary.

**Review by rowanc1 — APPROVED** [review]
This looks great! :) Thanks again @agoose77 for your work on this.

**Comment by rowanc1** [comment]
That sounds great. I will merge this in and may start come back to you with questions very shortly about how things are working. It will take me a bit of time to get into the flow of developing jupyter-lab extensions and seeing what responsibilities `jupyterlab-markup` is taking on. I think we may need some deeper integrations into the math (mostly around labelling and cross-referencing) than is currently available - am lookking forward to discussing that with you as I gain understanding there.

**Comment by rowanc1** [comment]
Thanks again @agoose77! 🚀

**Pull request merged**
